name: Build and Lint

on: [push, pull_request]

jobs:
    build:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                # the Node.js versions to build on
                node-version: [14.17.x, 16.x, 18.x, 20.x]

        steps:
            - uses: actions/checkout@v2

            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v2
              with:
                  node-version: ${{ matrix.node-version }}

            - name: Install dependencies
              run: yarn install

            - name: Lint the project
              run: yarn run lint

            - name: Build the project
              run: yarn run build
              env:
                  CI: true
